app/__init__.py
from flask import Flask

def create_app(config:dict):
    app = Flask(__name__)
    app.config.update(config)

    from .views.resume_builder import resume_builder
    app.register_blueprint(resume_builder)

    return app

app/views/resume_builder.py
from flask import Blueprint, render_template, request, session, redirect, url_for, g, abort, make_response, flash
from ..userform import UserForm
from ..functions import resume_data_required, get_all_fonts_name, font_exists, get_font
from ..config import TEMPLATES, TEMPLATES_PATH


resume_builder = Blueprint("ResumeBuilder", __name__)


@resume_builder.route("/", methods=["GET", "POST"])
def create_resume():
    current_user_form = UserForm()
    if request.method == "POST":
        current_user_form.from_request()
        current_user_form.validate()
        session.permanent = True
        session["resume-data"] = current_user_form.resume_data
        if len(current_user_form.errors) > 0:
            return redirect(url_for(".create_resume"))
        return redirect(url_for(".select_template"))

    current_user_form.from_session("resume-data")
    current_user_form.validate()

    return render_template(
        "resume_builder/create_resume.html",
        title="Build New Resume",
        resume_formdata=current_user_form.resume_data,
        resume_formdata_errors=current_user_form.errors,
    )


@resume_builder.route("/select-template")
@resume_data_required
def select_template():
    return render_template(
        "resume_builder/select_template.html",
        title="Select template for Resume",
        all_fonts=get_all_fonts_name(),
        available_templates=TEMPLATES
    )


@resume_builder.route("/preview")
@resume_data_required
def preview_and_save():
    TEMPLATE_NAME = request.args.get("template-name","").upper()
    HEADING_FONT = request.args.get("heading-font","")
    PARAGRAPH_FONT = request.args.get("paragraph-font","")
    if TEMPLATE_NAME not in TEMPLATES or\
        font_exists(HEADING_FONT) is False or\
        font_exists(PARAGRAPH_FONT) is False:
        flash("Please select template and fonts to view preview!")
        return redirect(url_for(".select_template"))

    current_user_form = g.user_form

    if request.args.get("form") == "iframe":
        return render_template(
            TEMPLATES_PATH[TEMPLATE_NAME],
            formdata=current_user_form.resume_data,
            HEADING_FONT=get_font(HEADING_FONT),
            PARAGRAPH_FONT=get_font(PARAGRAPH_FONT),
            type=type
        )

    elif request.args.get("form") == "download":
        HTML_DATA = render_template(
            TEMPLATES_PATH[TEMPLATE_NAME],
            formdata=current_user_form.resume_data,
            HEADING_FONT=get_font(HEADING_FONT),
            PARAGRAPH_FONT=get_font(PARAGRAPH_FONT),
            type=type
        )
        response = make_response(HTML_DATA)
        response.headers.add("Content-Disposition", 'attachment', filename='resume.html')
        return response
        

    elif request.args.get("form") is not None:
        abort(400)

    return render_template(
        "resume_builder/preview.html",
        title="Resume preview",
    )

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{title}}{{ " - " if title }}Resume builder</title>
    <meta name="description" content="Resume builder is an online tool that you can use to create a resume by providing necessary information.">
    <link rel="stylesheet" href="{{url_for('static', filename='css/main.css')}}">
    {% block head %}{% endblock %}
</head>
<body>
    <div class="main-container">
        <div class="main-head">
            <h1><a href="/">Resume builder</a></h1>
        </div>
        <div class="stages">
            <a href="{{ url_for('ResumeBuilder.create_resume') }}" class="stage {{'active' if request.endpoint == 'ResumeBuilder.create_resume'}}">
                <span class="stage-index">1</span>
                <span class="stage-name">Enter information</span>
            </a>
            <a href="{{ url_for('ResumeBuilder.select_template') }}"  class="stage {{'active' if request.endpoint == 'ResumeBuilder.select_template'}}">
                <span class="stage-index">2</span>
                <span class="stage-name">Select Template</span>
            </a>
            <a href="{{ url_for('ResumeBuilder.preview_and_save') }}" class="stage {{'active' if request.endpoint == 'ResumeBuilder.preview_and_save'}}">
                <span class="stage-index">3</span>
                <span class="stage-name">Preview & Save</span>
            </a>
        </div>
        {% with msgs = get_flashed_messages() %}
        <div class="messages">
            {% for msg in msgs %}
            <div class="msg">{{msg}}</div>
            {% endfor %}
        </div>
        {% endwith %}
        {% block body %}{% endblock %}
    </div>
    <a href="https://github.com/hakiKhuva/resume-builder" id="source-code-anchor">
        <span>View Source</span>
    </a>
</body>
</html>

app/templates/resume_builder/preview.html
{% extends "base.html" %}

{% block head %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/preview.css') }}">
<script src="https://unpkg.com/feather-icons"></script>
{% endblock %}

{% block body %}
<div class="btns">
    <button id="print-btn" class="btn" type="button">
        <i data-feather="printer" width="18px" height="18px"></i>
        <span>PRINT</span>
    </button>
    <a href="{{request.url}}&form=download" class="btn" target="_blank">
        <i data-feather="download-cloud" width="18px" height="18px"></i>
        <span>DOWNLOAD HTML</span>
    </a>
</div>
<div class="preview-container">
<iframe src="{{request.url}}&form=iframe" frameborder="0"></iframe>
</div>
<script>
    document.querySelector("#print-btn").addEventListener("click", e => {
        const win = window.open("{{request.url|safe}}&form=iframe")
        win.print()
        win.addEventListener("afterprint", e => {
            win.close()
        })
    })
    feather.replace()
</script>
{% endblock %}

app/templates/resume_builder/select_template.html
{% extends 'base.html' %}

{% block head %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/form.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='css/template.css') }}">
{% endblock %}

{% block body %}
<div class="form-container">
    <script>
        const changeTemplate = (e) => {
            if(e){
                const CURRENT_TEMPLATE = e.dataset["template"];
                document.querySelector("#template-name").value = CURRENT_TEMPLATE;
                document.querySelectorAll("[data-template]").forEach(templateElement => {
                    templateElement.classList.remove("selected");
                })
                e.classList.add("selected")
            }
        }
    </script>
    <form action="{{ url_for('ResumeBuilder.preview_and_save') }}" method="GET">
        <div class="block-container">
            <h2 class="resume-head">Templates</h2>
            <input type="hidden" value="{{ available_templates[0].lower() }}" name="template-name" id="template-name" />
            <div class="templates-container">
                {% for template in available_templates %}
                <button type="button" class="template {{ 'selected' if available_templates.index(template) == 0 }}" data-template="{{template.lower()}}" onclick="changeTemplate(this);">
                    <p>{{template}}</p>
                </button>
                {% endfor %}
            </div>
        </div>
        <div class="block-container">
            <h2 class="resume-head">Fonts</h2>
            <div class="label">
                <label for="heading-font">Heading font</label>
                <select name="heading-font" class="input" id="heading-font">
                    <option disabled selected>Select heading font</option>
                    {% for font in all_fonts %}
                    <option value="{{font}}">{{font}}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="label">
                <label for="paragraph">Paragraph font</label>
                <select name="paragraph-font" class="input" id="paragraph-font">
                    <option disabled selected>Select paragraph font</option>
                    {% for font in all_fonts %}
                    <option value="{{font}}">{{font}}</option>
                    {% endfor %}
                </select>
            </div>
        </div>
        <div class="block-container">
            <h2 class="resume-head">Next step</h2>
            <button type="submit" class="submit-btn">Preview</button>
        </div>
    </form>
</div>
{% endblock %}